---

plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
